<?php

return [
    'add_task'                    => 'Aggiungi lavoro',
    'add_timer'                   => 'Aggiungi timer',
    'bill_task'                   => 'Fattura lavoro',
    'bill_tasks'                  => 'Fattura lavori',
    'bill_to_existing_invoice'    => 'Aggiungi a fattura esistente',
    'bill_to_new_invoice'         => 'Aggiungi ad una nuova fattura',
    'billed_tasks'                => 'Lavori fatturati',
    'billed_hours'                => 'Ore fatturate',
    'bulk_actions'                => 'Azioni di massa',
    'choose_invoice_to_bill'      => 'Scegli fattura',
    'close'                       => 'Chiudi',
    'confirm_delete_project'      => 'Eliminare questo progetto cancellerà anche ogni lavoro e ogni timer ad esso associati. Sei sicuro?Deleting this project will delete any tasks and timers associated with it. Are you sure?',
    'confirm_delete_task'         => 'Eliminare un lavoro cancellerà anche ogni timer as esso associato. Sei sicuro?',
    'create_project'              => 'Crea progetto',
    'delete_project'              => 'Elimina progetto',
    'delete_task'                 => 'Elimina lavoro',
    'delete_tasks'                => 'Elimina lavori',
    'delete_timer'                => 'Elimina timer',
    'edit_project'                => 'Modifica progetto',
    'edit_task'                   => 'Modifica lavoro',
    'hourly_charge'               => 'Spesa oraria',
    'hourly_rate'                 => 'Tariffa oraria',
    'hours'                       => 'Ore',
    'how_to_bill'                 => 'Come vuoi fatturare questi lavori?',
    'project'                     => 'Progetto',
    'projects'                    => 'Progetti',
    'project_name'                => 'Nome progetto',
    'show_timers'                 => 'Visualizza timer',
    'start_time'                  => 'Ora di inizio',
    'start_timer'                 => 'Attiva il timer',
    'stop_time'                   => 'Ora di fine',
    'stop_timer'                  => 'Blocca il timer',
    'submit_and_add_another_task' => 'Invia e inserisci un altro lavoro',
    'submit_and_close'            => 'Invia e chiudi',
    'task'                        => 'Lavoro',
    'task_notice'                 => 'Clicca su Aggiungi lavoro per iniziare ad aggiungere lavori a questo progetto.',
    'tasks'                       => 'Lavori',
    'time_tracking'               => 'Time Tracking',
    'timers'                      => 'Timer',
    'timesheet'                   => 'Scheda attività',
    'total_hours'                 => 'Ore totali',
    'unbilled_hours'              => 'Ore non fatturate',
];